# -*- coding: utf-8 -*-
"""
Django settings for DevDoc project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.contrib.messages import constants as messages
from django.core.urlresolvers import reverse_lazy

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Message
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'secret'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = '*'


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'oauth',
    'home',
    'top',
    'settings',
    'editor',
    'render',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'DevDoc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'social.apps.django_app.context_processors.backends',
            ],
        },
    },
]

WSGI_APPLICATION = 'DevDoc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'devdoc',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'TIME_ZONE': 'Asia/Tokyo',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

OUTPUT_FORMAT = '%Y/%m/%d %H:%M:%S'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Login
AUTH_USER_MODEL = 'oauth.OAuthUser'
LOGIN_ERROR_URL = 'top:index'
LOGIN_URL = reverse_lazy('social:begin', kwargs={'backend': 'evernote-sandbox'})
# LOGIN_URL = reverse_lazy('social:begin', kwargs={'backend': 'evernote'})
LOGIN_REDIRECT_URL = 'home:index'

# Evernote OAuth
INSTALLED_APPS += ('social.apps.django_app.default',)

AUTHENTICATION_BACKENDS = (
    'social.backends.evernote.EvernoteSandboxOAuth',
    'social.backends.evernote.EvernoteOAuth',
    'django.contrib.auth.backends.ModelBackend',
)

EVERNOTE_DEBUG = True
# Evernote Dev API Key

# Evernote Product API Key

# Link from Evernote
LINK_EVERNOTE_DEV = 'http://localhost:8000/render/?guid='
LINK_EVERNOTE_PRODUCT = 'http://localhost:8000/render/?guid='

# Evernote Source info.
EN_SOURCE_APP = 'OSC_DevDoc'
EN_SOURCE = 'OSC'
# Evernote content class.
EN_CONTENT_CLASS = 'OSC.DevDoc'

# django-jenkins
INSTALLED_APPS += ('django_jenkins',)

PROJECT_APPS = (
    'editor',
    'home',
    'oauth',
    'render',
    'settings',
    'top',
)

JENKINS_TASKS = (
    'django_jenkins.tasks.run_pep8',
)

JENKINS_TEST_RUNNER = 'django_jenkins.runner.CITestSuiteRunner'

PEP8_RCFILE = 'pep8.ini'
